# Generated by Django 2.2.2 on 2019-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus1', '0003_auto_20190621_1422'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_ids',
        ),
        migrations.AddField(
            model_name='student',
            name='stud',
            field=models.IntegerField(default='0558'),
        ),
    ]
