# Generated by Django 2.2.2 on 2019-06-21 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus1', '0004_auto_20190621_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='stud',
            field=models.IntegerField(default='8420'),
        ),
    ]
