# Generated by Django 2.2.2 on 2019-06-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus1', '0006_auto_20190621_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentfake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_ID', models.IntegerField()),
                ('branch', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='stud',
        ),
        migrations.RemoveField(
            model_name='student',
            name='stude',
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.IntegerField(default='0380'),
        ),
    ]
